version: "3"
services:
  testnlog-service:
    container_name: testnlog-service
    hostname: testnlog-service
    build:
      context: ./TestNLogLayoutsForELK
      dockerfile: Dockerfile
    volumes:
      - test:/app/logs
volumes:
  test:
    external: true