FROM mcr.microsoft.com/dotnet/sdk:6.0.201-bullseye-slim-arm32v7 AS build-env
WORKDIR /app

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out -r linux-arm

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:6.0.0-focal-arm32v7
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "TestNLogLayoutsForELK.dll"]
